export const SET_LIBRARY = 'SET_LIBRARY';
export const GET_COFFEE_SHOPS = 'GET_COFFEE_SHOPS';
export const SET_DIRECTIONS_INSTRUCTIONS = 'SET_DIRECTIONS_INSTRUCTIONS';
export const CLEAR_SESSION_ID = 'CLEAR_SESSION_ID';
export const SET_DIRECTIONS_LOCATION = 'SET_DIRECTIONS_LOCATION';
export const SET_DIRECTIONS_MODE = 'SET_DIRECTIONS_MODE';